### PR TITLE
Update to PSR-4

### PR DESCRIPTION
**Pull request by ellisonpatterson**
Not sure if this could be done but would make using the package much easier :)

### CODE REVIEW

**Comment by OleMchls** [comment]
HeY @ellisonpatterson thanks for your contribution! 

I wonder why to remove the PSR-0 part?

**Comment by ellisonpatterson** [comment]
I believe it's deprecated :)

https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-0.md

**Comment by OleMchls** [comment]
@ellisonpatterson as you might have guessed I'm not into PHP anymore :D Thanks for pointing me to this and again thanks for your help! :)

**Comment by ellisonpatterson** [comment]
Just to confirm, everything works perfectly :D

**Pull request merged**
